# Generated by Django 3.0.4 on 2020-08-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_video_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
